- name: Create Jenkins Jobs
  hosts: local
  mjobs:
    - { job_name: "cart", repo_name: "https://github.com/krish596/cart" }
  sjobs:
    - { job_name: "roboshop-terraform", repo_name: "https://github.com/krish596/roboshop-terraform" }
