- name: Copy Conf File - {{ item.folder_name }}
  ansible.builtin.template:
    src: folder.xml
    dest: /tmp/folder.xml


- name: Create Job - {{ item.folder_name }}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{ item.folder_name }}"
    password: admin123
    url: http://172.31.84.115:8080
    user: admin