- name: Create Folder
  ansible.builtin.include_tasks:
    file: folders.yml

  loop: "{{ folders }}"

- name: Create Multibranch Pipeline Job
  ansible.builtin.include_tasks:
    file: mjob.yml

  loop: "{{ mjobs }}"

- name: Create Single Branch Pipeline Job
  ansible.builtin.include_tasks:
    file: sjob.yml

  loop: "{{ sjobs }}"