- name: Copy Conf File - {{ item.job_name }}
  ansible.builtin.template:
    src: mjob.xml
    dest: /tmp/mjob.xml


- name: Create Job - {{ item.job_name }}
  community.general.jenkins_job:
    config: "{{ lookup('mjob.xml', '/tmp/mjob.xml') }}"
    name: "{{item.job_name}}"
    password: admin123
    url: http://172.31.84.115:8080
    user: admin